/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CongratulationsModal: typeof import('./components/modalComponent/congratulationsModal.vue')['default']
    FailedModal: typeof import('./components/modalComponent/failedModal.vue')['default']
    GameButton: typeof import('./components/numberGamesLevel/gameButton.vue')['default']
    GameCard: typeof import('./components/numberGamesLevel/GameCard.vue')['default']
    GameLevelsSkeleton: typeof import('./components/gameLevels/gameLevelsSkeleton.vue')['default']
    GamesLevelsApp: typeof import('./components/gameLevels/gamesLevelsApp.vue')['default']
    GameTemplateLevel1: typeof import('./components/games/templates/GameTemplateLevel1.vue')['default']
    GameTemplateLevel10: typeof import('./components/games/templates/GameTemplateLevel10.vue')['default']
    GameTemplateLevel2: typeof import('./components/games/templates/GameTemplateLevel2.vue')['default']
    GameTemplateLevel3: typeof import('./components/games/templates/GameTemplateLevel3.vue')['default']
    GameTemplateLevel4: typeof import('./components/games/templates/GameTemplateLevel4.vue')['default']
    GameTemplateLevel5: typeof import('./components/games/templates/GameTemplateLevel5.vue')['default']
    GameTemplateLevel6: typeof import('./components/games/templates/GameTemplateLevel6.vue')['default']
    GameTemplateLevel7: typeof import('./components/games/templates/GameTemplateLevel7.vue')['default']
    GameTemplateLevel8: typeof import('./components/games/templates/GameTemplateLevel8.vue')['default']
    GameTemplateLevel9: typeof import('./components/games/templates/GameTemplateLevel9.vue')['default']
    GameView: typeof import('./components/games/gameView.vue')['default']
    HomeApp: typeof import('./components/homePage/HomeApp.vue')['default']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonImg: typeof import('@ionic/vue')['IonImg']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonModal: typeof import('@ionic/vue')['IonModal']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonSpinner: typeof import('@ionic/vue')['IonSpinner']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    NumberGamesLevelApp: typeof import('./components/numberGamesLevel/numberGamesLevelApp.vue')['default']
    ProfileApp: typeof import('./components/profile/profileApp.vue')['default']
    ProfileForm: typeof import('./components/auth/profile/components/profileForm.vue')['default']
    ProgressApp: typeof import('./components/progress/progressApp.vue')['default']
    RegisterData: typeof import('./components/initialData/registerData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplashScreen: typeof import('./components/splashScreen/SplashScreen.vue')['default']
  }
}
