/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    GamesApp: typeof import('./components/gameLevels/gamesApp.vue')['default']
    GamesLevelsApp: typeof import('./components/gameLevels/gamesLevelsApp.vue')['default']
    GameView: typeof import('./components/games/gameView.vue')['default']
    HomeApp: typeof import('./components/homePage/HomeApp.vue')['default']
    HomePage: typeof import('./components/homePage/HomePage.vue')['default']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonCardHeader: typeof import('@ionic/vue')['IonCardHeader']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonImg: typeof import('@ionic/vue')['IonImg']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonSpinner: typeof import('@ionic/vue')['IonSpinner']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    Level1Game: typeof import('./components/games/level1Game.vue')['default']
    NumberGamesLevelApp: typeof import('./components/numberGamesLevel/numberGamesLevelApp.vue')['default']
    ProfileApp: typeof import('./components/profile/profileApp.vue')['default']
    ProgressApp: typeof import('./components/progress/progressApp.vue')['default']
    RegisterData: typeof import('./components/initialData/registerData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplashScreen: typeof import('./components/splashScreen/SplashScreen.vue')['default']
  }
}
